//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H1EMU_Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H1EMU_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Hover {
            get {
                object obj = ResourceManager.GetObject("Arrow_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Pressed {
            get {
                object obj = ResourceManager.GetObject("Arrow_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AuthKey {
            get {
                object obj = ResourceManager.GetObject("AuthKey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Discord {
            get {
                object obj = ResourceManager.GetObject("Discord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Discord_Pressed {
            get {
                object obj = ResourceManager.GetObject("Discord_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Hover {
            get {
                object obj = ResourceManager.GetObject("Exit_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit_Pressed {
            get {
                object obj = ResourceManager.GetObject("Exit_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_Hover {
            get {
                object obj = ResourceManager.GetObject("Folder_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_Pressed {
            get {
                object obj = ResourceManager.GetObject("Folder_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap H1EmuIcon {
            get {
                object obj = ResourceManager.GetObject("H1EmuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap H1EmuLogo {
            get {
                object obj = ResourceManager.GetObject("H1EmuLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Language {
            get {
                object obj = ResourceManager.GetObject("Language", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimise {
            get {
                object obj = ResourceManager.GetObject("Minimise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimise_Hover {
            get {
                object obj = ResourceManager.GetObject("Minimise_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimise_Pressed {
            get {
                object obj = ResourceManager.GetObject("Minimise_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NextButton {
            get {
                object obj = ResourceManager.GetObject("NextButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NextButton_Hover {
            get {
                object obj = ResourceManager.GetObject("NextButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OfflineImage {
            get {
                object obj = ResourceManager.GetObject("OfflineImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Padlock {
            get {
                object obj = ResourceManager.GetObject("Padlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrevButton {
            get {
                object obj = ResourceManager.GetObject("PrevButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrevButton_Hover {
            get {
                object obj = ResourceManager.GetObject("PrevButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Server {
            get {
                object obj = ResourceManager.GetObject("Server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Server_Hover {
            get {
                object obj = ResourceManager.GetObject("Server_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Server_Pressed {
            get {
                object obj = ResourceManager.GetObject("Server_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shield {
            get {
                object obj = ResourceManager.GetObject("Shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowPassword {
            get {
                object obj = ResourceManager.GetObject("ShowPassword", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowPassword_Hover {
            get {
                object obj = ResourceManager.GetObject("ShowPassword_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowPassword_Pressed {
            get {
                object obj = ResourceManager.GetObject("ShowPassword_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Signika {
            get {
                object obj = ResourceManager.GetObject("Signika", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StandardButton {
            get {
                object obj = ResourceManager.GetObject("StandardButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StandardButton_Hover {
            get {
                object obj = ResourceManager.GetObject("StandardButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StandardButton_Pressed {
            get {
                object obj = ResourceManager.GetObject("StandardButton_Pressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;A new update is available, would you like to update now?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;UPDATE&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Update Version&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Press lau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources {
            get {
                return ResourceManager.GetString("StringResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Ново обновление е налично,желаете ли да го изтеглите?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;Обновление&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Версията&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Натисни пусни  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_bg_BG {
            get {
                return ResourceManager.GetString("StringResources_bg_BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Eine neue Aktualisierung ist verfügbar, möchtest du die Aktualisierung jetzt ausführen?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;Aktualisierung&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Aktualisieren&lt;/system:String&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_de_DE {
            get {
                return ResourceManager.GetString("StringResources_de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Une mise à jour est disponible, voulez vous la télécharger?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;Mise à jour&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Màj Version&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Appu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_fr_FR {
            get {
                return ResourceManager.GetString("StringResources_fr_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Nova verzija je dostupna, želite li ažurirati?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;AŽURIRANJE&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Verzija&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Pritisnite pokreni da  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_hr {
            get {
                return ResourceManager.GetString("StringResources_hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Een niewe versie is beschikbaar, wilt u deze instaleren?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;INSTALEREN&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Werk bij&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Klik opstar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_nl_NL {
            get {
                return ResourceManager.GetString("StringResources_nl_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Dostępna jest nowa aktualizacja, Czy chcesz zaktualizować teraz?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;AKTUALIZACJA&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Wersja&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Uży [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_pl_PL {
            get {
                return ResourceManager.GetString("StringResources_pl_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Uma nova atualização está disponível, quer atualizar agora?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;ATUALIZAR&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Versão da atualização&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Cli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_pt_PT {
            get {
                return ResourceManager.GetString("StringResources_pt_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Доступно новое обновление, хотите обновить сейчас?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;ОБНОВИТЬ&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Обновление&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Нажмите здесь, чт [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_ru_RU {
            get {
                return ResourceManager.GetString("StringResources_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Yeni bir güncelleme var, yüklemek ister misiniz?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;GÜNCELLEME&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Versiyonu&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Yerel tekli sunucu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_tr_TR {
            get {
                return ResourceManager.GetString("StringResources_tr_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;有新的更新可用，是否立即更新?&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;更新&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;最新版本&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;按 本地服务器 按键启动本地服务器&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;ite [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_zh_CN {
            get {
                return ResourceManager.GetString("StringResources_zh_CN", resourceCulture);
            }
        }
    }
}
