//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H1Emu_Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H1Emu_Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Assets_256 {
            get {
                object obj = ResourceManager.GetObject("Assets_256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Assets_257 {
            get {
                object obj = ResourceManager.GetObject("Assets_257", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Assets_258 {
            get {
                object obj = ResourceManager.GetObject("Assets_258", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Assets_259 {
            get {
                object obj = ResourceManager.GetObject("Assets_259", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackgroundArt {
            get {
                object obj = ResourceManager.GetObject("BackgroundArt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CustomClientConfig {
            get {
                object obj = ResourceManager.GetObject("CustomClientConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Game_Patch_2016 {
            get {
                object obj = ResourceManager.GetObject("Game_Patch_2016", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grain {
            get {
                object obj = ResourceManager.GetObject("Grain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap H1EmuIcon {
            get {
                object obj = ResourceManager.GetObject("H1EmuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap H1EmuLogo {
            get {
                object obj = ResourceManager.GetObject("H1EmuLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] H1EmuVoiceClient {
            get {
                object obj = ResourceManager.GetObject("H1EmuVoiceClient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] H1Z1_BE {
            get {
                object obj = ResourceManager.GetObject("H1Z1_BE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] H1Z1_FP {
            get {
                object obj = ResourceManager.GetObject("H1Z1_FP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Locales {
            get {
                object obj = ResourceManager.GetObject("Locales", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lz4 {
            get {
                object obj = ResourceManager.GetObject("lz4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Node_Files {
            get {
                object obj = ResourceManager.GetObject("Node_Files", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Placeholder {
            get {
                object obj = ResourceManager.GetObject("Placeholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrimaryButton {
            get {
                object obj = ResourceManager.GetObject("PrimaryButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Server_Quickstart {
            get {
                object obj = ResourceManager.GetObject("Server_Quickstart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Signika {
            get {
                object obj = ResourceManager.GetObject("Signika", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Sound_Banks {
            get {
                object obj = ResourceManager.GetObject("Sound_Banks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Необходима е нова актуализация за игра, моля, изчакайте.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;Обновление&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Версия&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Моля Изчакай&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_bg_BG {
            get {
                return ResourceManager.GetString("StringResources_bg_BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Zum spielen ist ein neues update erforderlich. Bitte warten sie.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;Aktualisierung&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Aktualisieren&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_de_DE {
            get {
                return ResourceManager.GetString("StringResources_de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;A new update is required to play, please wait.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;UPDATE&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Version&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Please wait&lt;/system:String [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_en_EN {
            get {
                return ResourceManager.GetString("StringResources.en-EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Se requiere una nueva actualización para jugar, espera.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;ACTUALIZAR&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Versión&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Espere por fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_es_ES {
            get {
                return ResourceManager.GetString("StringResources_es_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Une nouvelle mise à jour est nécessaire pour jouer, veuillez patienter.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;Mise à jour&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Màj Version&lt;/system:String&gt;
        ///    &lt;system:String x:Key= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_fr_FR {
            get {
                return ResourceManager.GetString("StringResources.fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Novi update je potreban za igranje, molim pričekajte.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;AŽURIRANJE&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Verzija&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Molimo pričekaj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_hr_HR {
            get {
                return ResourceManager.GetString("StringResources.hr-HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Er is een nieuwe update vereist om te kunnen spelen. Een ogenblik geduld.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;INSTALEREN&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Versie&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;ite [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_nl_NL {
            get {
                return ResourceManager.GetString("StringResources_nl_NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Aby zagrać, wymagana jest nowa aktualizacja. Proszę czekać.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;AKTUALIZACJA&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Wersja&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Proszę c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_pl_PL {
            get {
                return ResourceManager.GetString("StringResources_pl_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Uma nova atualização é necessária para jogar, aguarde.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;ATUALIZAR&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Versão&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Por favor, esper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_pt_PT {
            get {
                return ResourceManager.GetString("StringResources_pt_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Для игры требуется новое обновление, подождите.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;ОБНОВИТЬ&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Обновление&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Пожалуйста подождите&lt;/syste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_ru_RU {
            get {
                return ResourceManager.GetString("StringResources_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;En ny uppdatering krävs för att spela, vänligen vänta.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;UPPDATERA&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Version&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Var god vänta&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_se_SE {
            get {
                return ResourceManager.GetString("StringResources.se-SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;Oynamak için yeni bir güncelleme gerekiyor, lütfen bekleyin.&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;GÜNCELLEME&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;Versiyonu&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;Lütfen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_tr_TR {
            get {
                return ResourceManager.GetString("StringResources_tr_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///                    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///                    xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;system:String x:Key=&quot;item1&quot;&gt;启动器必须在更新后才可以使用，请等待更新。&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item2&quot;&gt;更新&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item3&quot;&gt;最新版本&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item4&quot;&gt;请稍等&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;item8&quot;&gt;运行游戏 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_zh_CN {
            get {
                return ResourceManager.GetString("StringResources_zh_CN", resourceCulture);
            }
        }
    }
}
